apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  type: LoadBalancer
  loadBalancerIP: 18.141.31.199
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  externalIPs:
          - '18.141.31.199'   
  selector:
    app: api-gateway
