apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appointment-service
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - image: ahhmedhs/project-appointment-service
          name: appointment-service
          env:
            - name: eureka-server
              value: "eureka-server"
          ports:
            - containerPort: 8060
      restartPolicy: Always
