apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authentication-service
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - image: ahhmedhs/project-authentication-service
          name: authentication-service
          env:
            - name: eureka-server
              value: "eureka-server"
          ports:
            - containerPort: 9100
      restartPolicy: Always
