apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - image: ahhmedhs/project-email-service
          name: email-service
          env:
            - name: eureka-server
              value: "eureka-server"
          ports:
            - containerPort: 8075
      restartPolicy: Always
