apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-server
  name: eureka-server
spec:
  ClusterIP: none      
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    app: eureka-server
